name: Build


permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write


on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream uv version (leave blank for latest)'
        required: false
        type: string


jobs:
  check-current:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
    - name: Get current version
      id: get-version
      run: |
        if [[ -z $version ]]; then
          version=$(gh release view --repo astral-sh/uv --json name --jq ".name")
        fi
        # if we didn't already release $version from this repo, set the output param
        gh release view $version || echo version=$version >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VERSION: ${{ inputs.version }}


  build:
    runs-on: ubuntu-latest
    needs: check-current
    if: ${{ needs.check-current.outputs.version != '' }}
    env:
      VERSION: ${{ needs.check-current.outputs.version }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - id: restore
      name: Restore
      run: dotnet restore

    - id: pack
      name: Download and pack assets
      run: dotnet pack
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # - name: Attest
    #   uses: actions/attest-build-provenance@v1
    #   with:
    #     subject-path: 'artifacts/package/release/*'

    - name: Compute checksums
      run: |
        pushd artifacts/package/release
        for file in *;
          do sha256sum -b $file > $file.sha256;
        done
        popd

    - id: push
      name: Push nuget packages
      run: |
        dotnet nuget push 'artifacts/package/release/*.nupkg' --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
        dotnet nuget push 'artifacts/package/release/*.nupkg' --source https://nuget.pkg.github.com/benjamin-hodgson/index.json -k ${{ github.token }}

    - uses: actions/upload-artifact@v4
      if: steps.pack.conclusion != 'cancelled' && steps.pack.conclusion != 'skipped'
      with:
        name: packages
        path: artifacts/package/release

    - name: Create Github Release
      if: steps.push.conclusion == 'success'
      run: gh release create $VERSION ./artifacts/package/release/*
      env:
        GITHUB_TOKEN: ${{ github.token }}
